# -*- coding: utf-8 -*-
"""Introtoportfolioopt2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11zsLeIMFx82aUfKFhr9j30njnK4e3-Qm
"""

